model_params:
  _key_value: True
  generator:
    model: SimpleGenerator
    noise_dim: 16
  discriminator:
    model: SimpleDiscriminator


args:
  expdir: "examples/mnist_gans"
  logdir: "./examples/logs/mnist_gan"


stages:

  data_params:
    batch_size: 64
    num_workers: 1

  state_params:
    num_epochs: 100
    main_metric: &reduce_metric loss_g
    minimize_metric: True
    batch_consistant_metrics: False

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    phase_manager:
      callback: PhaseManagerCallback
      # one of "all" (use all callbacks), "same" (same phases as in train)
      valid_mode: "all"
      train_phases:
        discriminator_train: 1
        generator_train: 1

    loss_g:
      _wrapper: &g_train_wrapper
        callback: CallbackPhaseBatchWrapper
        active_phases: [generator_train]
      callback: CriterionCallback
      input_key: "real_targets"
      output_key: "fake_logits"
      loss_key: loss_g
      prefix: loss_g

    loss_d_real:
      _wrapper: &d_train_wrapper
        callback: CallbackPhaseBatchWrapper
        active_phases: [discriminator_train]
      callback: CriterionCallback
      input_key: "real_targets"
      output_key: "real_logits"
      loss_key: loss_d_real
      prefix: loss_d_real
    loss_d_fake:
      _wrapper: *d_train_wrapper
      callback: CriterionCallback
      input_key: "fake_targets"
      output_key: "fake_logits"
      loss_key: loss_d_fake
      prefix: loss_d_fake
    optim_g:
      _wrapper: *g_train_wrapper
      callback: OptimizerCallback
      optimizer_key: generator
      loss_key: loss_g
    optim_d:
      _wrapper: *d_train_wrapper
      callback: OptimizerCallback
      optimizer_key: discriminator
      loss_key: [loss_d_real, loss_d_fake]
      prefix: loss_d
    visualizer:
      callback: VisualizationCallback
      output_keys: "fake_images"
      n_row: 5
      max_images: 25
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      _key_value: True
      generator:
        optimizer: Adam
        _model: ["generator"]
        lr: 0.0002
      discriminator:
        optimizer: Adam
        _model: ["discriminator"]
        lr: 0.0002
