model_params:
  model: SimpleNet

args:
  expdir: "_tests_mnist_stages"
  logdir: "./logs/mnist_simple"

stages:

  data_params:
    batch_size: 64
    num_workers: 0

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  criterion_params:
      criterion: SymmetricCrossEntropyLoss

  scheduler_params:
    scheduler: MultiStepLR
    milestones: [1]
    gamma: 0.3

  callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1, 3, 5]
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 3

  stage1:

    state_params:
      num_epochs: &num_epochs 2

    optimizer_params:
      optimizer: Adam
      layerwise_params:
        conv1.*:
          lr: 0.001
          weight_decay: 0.0003
      lr: 0.001
      weight_decay: 0.0001
      no_bias_weight_decay: True

  stage2:
    state_params:
      num_epochs: 1

    optimizer_params:
      load_from_previous_stage: True
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001
      no_bias_weight_decay: False
