model_params:
  model: Model
  # here can lay model params **kwargs

args:
  expdir: "src"  # path to your experiment
  logdir: "./logs/"  # path to logs

stages:
  data_params:
    batch_size: 64  # CHANGE ME
    num_workers: 1  # CHANGE ME

  stage_params:
    num_epochs: 2  # CHANGE ME
    main_metric: &reduced_metric loss  # loss for scheduler and checkpoint saver
    minimize_metric: True  # Change if you change `main_metric`

  criterion_params:
    criterion: CrossEntropyLoss # CHANGE ME

  scheduler_params:
    scheduler: MultiStepLR # CHANGE ME
    milestones: [10]
    gamma: 0.3

  callbacks_params:
    loss:
      callback: CriterionCallback
    optimizer:
      callback: OptimizerCallback
    scheduler:
      callback: SchedulerCallback
      reduced_metric: *reduced_metric
    saver:
      callback: CheckpointCallback

  stage1:

    optimizer_params:
      optimizer: Adam # CHANGE ME
      lr: 0.001
      weight_decay: 0.0001
