args:
  logdir: ./logs/_tests_rl_gym_dqn  #  change me
  expdir: null

  vis: 0
  infer: 0  #  change me
  valid: 1  #  change me
  train: 1  #  change me

db:
  db: RedisDB
  port: 12000
  prefix: gym-dqn  # TODO: remove

environment:
  environment: GymWrapper
  env_name: MountainCar-v0

  history_len: 3

  frame_skip: 2
  reward_scale: 0.01
  step_delay: 0.01

agents:
  critic:
    agent: ActionCritic

    state_net_params:  # state -> hidden representation
      observation_net_params:
        hiddens: [8]  # first hidden would be taken from state_shape
        layer_fn: Linear
        norm_fn: LayerNorm
        activation_fn: ReLU
        bias: false
      main_net_params:
        hiddens: [8, 8]
        layer_fn: Linear
        norm_fn: LayerNorm
        activation_fn: ReLU
        bias: false
    value_head_params:  # hidden representation -> ~policy
      in_features: 8  # out features would be taken from action_shape
      num_atoms: 1

#      distribution: categorical
#      num_atoms: 4
#      values_range: [-10.0, 10.0]

#      distribution: quantile
#      num_atoms: 4

algorithm:
  algorithm: DQN

  n_step: 1
  gamma: 0.99
  critic_tau: 0.01

  critic_loss_params:
    criterion: HuberLoss
    clip_delta: 10.0

  critic_optimizer_params:
    optimizer: Adam
    lr: 0.0003

  critic_scheduler_params:
    scheduler: MultiStepLR
    milestones: [2000000]  # batches
    gamma: 1.0

trainer:
  batch_size: 16               # transitions
  num_workers: 1
  epoch_len: 10                # batches

  replay_buffer_size: 100000   # transitions
  min_num_transitions: 32           # transitions

  save_period: 1               # epochs
  weights_sync_period: 1       # epochs
  target_update_period: 1      # batches

sampler:
  weights_sync_period: 1

  exploration_params:
    - exploration: EpsilonGreedy
      probability: 0.98
      eps_init: 1.0
      eps_final: 0.05
      annealing_steps: 20000

    - exploration: Greedy
      probability: 0.02

  valid_seeds: [
    1608637542,
    1273642419,
    1935803228,
    787846414,
    996406378,
  ]
