model_params:
  model: SimpleNet

runner_params:
  input_key: image

args:
  expdir: "mnist_simple"
  logdir: "./logs/mnist_simple"

stages:

  data_params:
    batch_size: 64
    num_workers: 0

  transform_params:
    _key_value: True

    train: &transform
      _key_value: True

      image:
        transform: Compose
        transforms:
          - transform: catalsyt.TensorToImage
          - transform: Normalize
            mean: [0.1307]
            std: [0.3081]
          - transform: catalsyt.ToTensor
    valid:
      transform: Compose
      transforms:
        - transform: catalsyt.TensorToImage
        - transform: Normalize
          mean: [0.1307]
          std: [0.3081]
        - transform: catalsyt.ToTensor

  criterion_params:
      criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: Adam
    lr: 0.001
    weight_decay: 0.0001

  stage1:
    state_params:
      num_epochs: &num_epochs 100

    callbacks_params:
      loss:
        callback: CriterionCallback
      optimizer:
        callback: OptimizerCallback
      finder:
        callback: LRFinder
        final_lr: 0.1
        num_steps: 1000
