args:
  logdir: ./logs/rl-gym-dqn  #  change me
  expdir: null

  vis: 0
  infer: 0  #  change me
  train: 1  #  change me

db:
  db: RedisDB
  port: 12000
  prefix: gym-dqn  # TODO: remove

environment:
  environment: GymWrapper
  env_name: LunarLander-v2

  history_len: 3

  frame_skip: 2
  reward_scale: 1.0
  step_delay: 0.01

agents:
  critic:
    agent: ActionCritic

    state_net_params:  # state -> hidden representation
      observation_net_params:
        hiddens: [128]  # first hidden would be taken from state_shape
        layer_fn: Linear
        norm_fn: LayerNorm
        activation_fn: ReLU
        bias: false
      main_net_params:
        hiddens: [128, 128]
        layer_fn: Linear
        norm_fn: LayerNorm
        activation_fn: ReLU
        bias: false
    value_head_params:  # hidden representation -> ~policy
      in_features: 128  # out features would be taken from action_shape
      num_atoms: 1

#      distribution: categorical
#      num_atoms: 64
#      values_range: [-300.0, 300.0]

#      distribution: quantile
#      num_atoms: 64

algorithm:
  algorithm: DQN

  n_step: 1
  gamma: 0.99
  critic_tau: 1.0

  critic_loss_params:
    criterion: HuberLoss
    clip_delta: 10.0

  critic_optimizer_params:
    optimizer: Adam
    lr: 0.0003

  critic_scheduler_params:
    scheduler: MultiStepLR
    milestones: [2000000]  # batches
    gamma: 1.0

trainer:
  batch_size: 256              # transitions
  num_workers: 1
  epoch_len: 500               # batches

  replay_buffer_size: 1000000  # transitions
  min_num_transitions: 5000    # transitions

  save_period: 1000            # epochs
  weights_sync_period: 1       # epochs
  target_update_period: 500    # batches

sampler:
  weights_sync_period: 1

  exploration_params:
    - exploration: Boltzmann
      probability: 0.5
      temp_init: 1.0
      temp_final: 0.5
      annealing_steps: 10000

    - exploration: EpsilonGreedy
      probability: 0.45
      eps_init: 1.0
      eps_final: 0.5
      annealing_steps: 10000

    - exploration: Greedy
      probability: 0.05