args:
  logdir: ./logs/rl-gym-reinforce  #  change me
  expdir: null

  vis: 0
  infer: 0  #  change me
  train: 4  #  change me

db:
  db: RedisDB
  port: 12000
  prefix: gym-reinforce  # TODO: remove

environment:
  environment: GymWrapper
  env_name: LunarLander-v2

  history_len: 3

  frame_skip: 2
  reward_scale: 1.0
  step_delay: 0.01

agents:
  actor:
    agent: Actor

    state_net_params:  # state -> hidden representation
      observation_net_params:
        hiddens: [32]  # first hidden would be taken from state_shape
        layer_fn: Linear
        norm_fn: LayerNorm
        activation_fn: ReLU
        bias: false
      main_net_params:
        hiddens: [32, 32]
        layer_fn: Linear
        norm_fn: LayerNorm
        activation_fn: ReLU
        bias: false
    policy_head_params:  # hidden representation -> ~policy
      in_features: 32  # out features would be taken from action_shape
      policy_type: categorical

algorithm:
  algorithm: REINFORCE

  n_step: 1
  gamma: 0.99

  entropy_reg_coefficient: 0.05

  actor_optimizer_params:
    optimizer: Adam
    lr: 0.0005

  actor_grad_clip_params:
    func: clip_grad_value_
    clip_value: 1.0

  actor_scheduler_params:
    scheduler: MultiStepLR
    milestones: [2000000]  # batches
    gamma: 1.0

trainer:
  batch_size: 256              # transitions
  num_workers: 1
  num_mini_epochs: 10
  min_num_trajectories: 5000
  min_num_transitions: 50000

  save_period: 100             # epochs

sampler:
  buffer_size: 1100

  valid_seeds: [1, 10, 1000, 10000, 42000]

  exploration_params:
    - exploration: NoExploration
      probability: 1.0
